version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  node-app:
    build: .
    container_name: node-app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/nodeDB
    ports:
      - "3000:3000"
